name: ymdy
description: 玉米电影ijkplayer模块.
publish_to: "none"

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  photo: ^0.4.8

  oktoast: ^2.1.7

  flutter_localizations:
    sdk: flutter
  intl: ">=0.15.8 <1.0.0"

  flutter_ijkplayer:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_translation: ^0.17.3

flutter:
  uses-material-design: true
  assets:
    - assets/
